run:
  timeout: 5m
  tests: true

linters:
  enable:
    - goconst
    - gocritic
    - govet
    - ineffassign
    - misspell
    - nakedret
    - staticcheck
    - unconvert
    - unparam
    - unused
    - bodyclose
    - dupl
    - gochecknoinits
    - gocyclo
    - errcheck

linters-settings:
  gocyclo:
    min-complexity: 20

issues:
  exclude:
    - "G104: Errors unhandled"
    - "SA9003: empty branch"
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - path: cmd/api/main.go
      linters:
        - errcheck
    - path: internal/service/link_service.go
      linters:
        - errcheck
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
